### ISSUE TITLE
Force https when accessing it

### ISSUE THREAD

**Issue by empeje** [pyconid/pyconid2021#47]
Hi Team,

I saw that the website is still in `http` at least the one that I found from Google.

It might be better to have the `https` which will helps with the SEO.

![Captura de Pantalla 2021-09-05 a la(s) 2 39 13](https://user-images.githubusercontent.com/11813607/132106168-afe8348c-d506-41fc-b53a-ae4ca2f910b5.png)

**Comment by ridhof** [comment]
Hi Empeje, thanks for letting us know.
I also had the same experience just a few hours ago when I was going to share the url to my acquaintance. Firefox was showing that I accessed a not secure website.

we will put this in backlog as an improvement and will use this issue for the update.

**Comment by tegarimansyah** [comment]
Hi @empeje , thank you for your finding.

I already make some tweaks to the HTTPS configuration. I tried incognito mode in chrome and firefox, for now, if I type `pycon.id`, it will be automatically using HTTPS. Traffic from google also gives me the same results.

Unless I write specifically HTTP in the URL, the site will use HTTPS. Not sure how we can redirect HTTP connection to HTTPS since this site host on github pages and `Enforce HTTPS` option is already been checked. I will ask the community later.

Please let me know how the result on your side

**Comment by empeje** [comment]
Looks good now.

<img width="622" alt="Captura de Pantalla 2021-09-06 a la(s) 9 52 45" src="https://user-images.githubusercontent.com/11813607/132154009-2615127d-8da2-4911-9bce-f7309b1bf3c9.png">

**Comment by ridhof** [comment]
seems like the issue has been solved, so I am going to close the issue for now.
![https://cdn.discordapp.com/attachments/750304684836651039/885162831035629618/unknown.png](https://cdn.discordapp.com/attachments/750304684836651039/885162831035629618/unknown.png)
